# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "teammembers" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"teamId" BIGINT NOT NULL,"userId" BIGINT NOT NULL,"password" VARCHAR NOT NULL,"admin" BOOLEAN DEFAULT false NOT NULL,"locked" BOOLEAN DEFAULT false NOT NULL,"createdAt" TIMESTAMP NOT NULL,"updatedAt" TIMESTAMP NOT NULL);
create unique index "idx_team_user" on "teammembers" ("teamId","userId");
create table "team" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"description" VARCHAR,"noAdmin" BOOLEAN DEFAULT false NOT NULL,"noRoot" BOOLEAN DEFAULT false NOT NULL,"createdAt" TIMESTAMP NOT NULL,"updatedAt" TIMESTAMP NOT NULL);
create table "users" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"email" VARCHAR NOT NULL,"password" VARCHAR NOT NULL,"admin" BOOLEAN DEFAULT false NOT NULL,"privateKey" VARCHAR NOT NULL,"publicKey" VARCHAR NOT NULL,"lastLoginAt" TIMESTAMP,"firstName" VARCHAR,"lastName" VARCHAR,"authMode" VARCHAR DEFAULT 'DBAuth' NOT NULL,"preferredLocale" VARCHAR DEFAULT 'en' NOT NULL,"createdAt" TIMESTAMP NOT NULL,"updatedAt" TIMESTAMP NOT NULL);
alter table "teammembers" add constraint "user_fk" foreign key("userId") references "users"("id") on update NO ACTION on delete NO ACTION;
alter table "teammembers" add constraint "team_fk" foreign key("teamId") references "team"("id") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "teammembers" drop constraint "user_fk";
alter table "teammembers" drop constraint "team_fk";
drop table "teammembers";
drop table "team";
drop table "users";

